// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6KPqB39yBL5Xgy8anlBi2JArlqhybxMA',
    appId: '1:366111527653:web:acb8b007fc72416bd83a0c',
    messagingSenderId: '366111527653',
    projectId: 'flutterfirebase-d0e08',
    authDomain: 'flutterfirebase-d0e08.firebaseapp.com',
    storageBucket: 'flutterfirebase-d0e08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJIa5Nb7s6lNP-t3pHSv6WBBcogIkXAs',
    appId: '1:366111527653:android:216fe406a468afd4d83a0c',
    messagingSenderId: '366111527653',
    projectId: 'flutterfirebase-d0e08',
    storageBucket: 'flutterfirebase-d0e08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5RB33464AktxiPVwceVMXblUm35xZq5I',
    appId: '1:366111527653:ios:a2623e47a068eb56d83a0c',
    messagingSenderId: '366111527653',
    projectId: 'flutterfirebase-d0e08',
    storageBucket: 'flutterfirebase-d0e08.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5RB33464AktxiPVwceVMXblUm35xZq5I',
    appId: '1:366111527653:ios:27763f07f60e8e47d83a0c',
    messagingSenderId: '366111527653',
    projectId: 'flutterfirebase-d0e08',
    storageBucket: 'flutterfirebase-d0e08.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
